SET foreign_key_checks = 0;
LOAD DATA LOCAL INFILE "node.dat"
INTO TABLE node
FIELDS ENCLOSED BY "\"" TERMINATED BY ","
;
LOAD DATA LOCAL INFILE "event.dat" 
INTO TABLE event 
FIELDS ENCLOSED BY "\"" TERMINATED BY ","
;
LOAD DATA LOCAL INFILE "detected_at_by.dat" 
INTO TABLE detected_at_by 
FIELDS ENCLOSED BY "\"" TERMINATED BY ","
;
LOAD DATA LOCAL INFILE "end_point.dat" 
INTO TABLE end_point 
FIELDS ENCLOSED BY "\"" TERMINATED BY ","
;
LOAD DATA LOCAL INFILE "user.dat" 
INTO TABLE user
FIELDS ENCLOSED BY "\"" TERMINATED BY ","
;
